github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
gitConfig:
  alias.st: status
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      poetry config virtualenvs.in-project true
      poetry install
    command: |
      poetry shell
vscode:
  extensions:
    - ms-python.python
